### ISSUE TITLE
How to export/import data?

### ISSUE THREAD

**Issue by bfontaine** [dokku/dokku-elasticsearch#156]
Hello,
I’m looking for `dokku elasticsearch:export` / `dokku elasticsearch:import` commands to back data up. What would be the best way to do that?
Thanks

**Comment by josegonzalez** [comment]
Does elasticsearch come with that sort of tool in xpack or something?

**Comment by bfontaine** [comment]
I don’t think so; all the solutions I found rely on an external tool (I use Elasticdump).

**Comment by josegonzalez** [comment]
Yeah so I don't ship anything but the official tools for any of the datastore plugins, as that creates a maintenance burden for me if they ever get deprecated. In this case, I'd recommend using an external tool.

Should Elasticsearch ever provide something official, I'll use that.
