### ISSUE TITLE
Where is elasticsearch.yml located?

### ISSUE THREAD

**Issue by bjornpost** [dokku/dokku-elasticsearch#16]
In my search query I have a custom score function. As scripting is disabled by default, currently I can't use inline scripts, nor indexed scripts. I'm trying to enable scripting, but I can't find the `elasticsearch.yml` config file. Where is it located? 

Ps: Great to see dokku providing elasticsearch instead of having to rely on an unmaintained plugin! Thanks!

**Comment by josegonzalez** [comment]
The `/usr/share/elasticsearch/data`directory is mounted into `/var/lib/dokku/services/elasticsearch/SERVICE_NAME/data`. You can stop your container, modify the config, and start it again.

Please close the issue if that helps!

**Comment by bjornpost** [comment]
The directory does not seem to contain `elasticsearch.yml`, just the raw data storage:

    /var/lib/dokku/services/elasticsearch/search01# tree -afL 3
    .
    ├── ./config
    ├── ./data
    │   └── ./data/elasticsearch
    │       └── ./data/elasticsearch/nodes
    ├── ./ID
    └── ./LINKS

**Comment by josegonzalez** [comment]
Interesting. I messed up and the file *should* be in `/var/lib/dokku/services/elasticsearch/SERVICE_NAME/config`, which mounts `/usr/share/elasticsearch/config` as mentioned [here](https://hub.docker.com/_/elasticsearch/#how-to-use-this-image). Really odd that you also don't have the [logging.yml](https://github.com/docker-library/elasticsearch/blob/c0cc86cddec0de3bd8fa01bcca5ef0c36fc7d255/1.7/Dockerfile#L39) either... Might this be a bug in the official docker image?

**Comment by bjornpost** [comment]
Just wanted to let you know that this issue is still there. I haven't used the official elasticsearch docker image, but there aren't any open issues related to this subject in their issue list. Can you reproduce this issue on your side?

**Comment by bjornpost** [comment]
@josegonzalez Quick update. Digged around a little further today:

    docker exec -it "containerid" bash
    cat /etc/init.d/elasticsearch | grep elasticsearch.yml
    CONF_FILE=$CONF_DIR/elasticsearch.yml

`$CONF_DIR` is set to `/etc/elasticsearch`. Seems like the config is not read at all from `/usr/share/elasticsearch/config` in my case. If I update my config in `/etc/elasticsearch/elasticsearch.yml`, everything works as expected.

Maybe `/var/lib/dokku/services/elasticsearch/SERVICE_NAME/config` should mount `/etc/elasticsearch`?

**Comment by josegonzalez** [comment]
Sorry, I haven't had time to dig into this issue.

From the hub entry, seems like someone had the same sort of issue re: installing shield plugin. I think this might be a bug in the documentation?

> God docker hub sucks. I wonder if it's open source so I can add simple shit like, idk, links to comments. Or a working password reset for people who don't remember the email they used...

**Comment by ProGM** [comment]
I found the same issue, I couldn't find `elasticsearch.yml`.

Here's my steps to fix this plugin installation:
```
$ dokku elasticsearch:create MYNAMEHERE
$ docker exec -it $(docker ps -a | grep MYNAMEHERE | grep docker-entrypoint | cut -f 1 -d " ") bash
$ mv /etc/elasticsearch/* /usr/share/elasticsearch/config
$ rm -rf /etc/elasticsearch
$ ln -s /usr/share/elasticsearch/config/ /etc/elasticsearch
$ exit
```

This also fixes logs, and makes it easier to install `shield`, if needed.

**Comment by josegonzalez** [comment]
Finally fixed the issue. Thanks @ProGM for digging into it, I used your instructions to construct what actually works :)
