### ISSUE TITLE
Elasticsearch 2.1 runs on `127.0.0.1` not `0.0.0.0` by default

### ISSUE THREAD

**Issue by cameronmaske** [dokku/dokku-elasticsearch#24]
Unlike <=1.7, 2.1 binds it's network to `127.0.0.1` ([docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html)). 

This means when a linked app tries to access it, it wouldn't be able to reach it. 

The solution is to manually to set `network.host: 0.0.0.0` in the `elasticsearch.yml` in `/var/lib/dokku/services/elasticsearch/<app>/config/elasticsearch.yml` then restart the container.

**Comment by rodcrespo** [comment]
+1 Thanks!
