### ISSUE TITLE
Update HEAP max memory

### ISSUE THREAD

**Issue by GabKlein** [dokku/dokku-elasticsearch#39]
I there,

What would be the best way to limit the elasticsearch memory consumption ? 
I'm running multitude of feature branches (CD env) and ES is taking all the memory.

**Comment by josegonzalez** [comment]
The `/usr/share/elasticsearch/config` container directory is mounted at `/var/lib/dokku/services/elasticsearch/SERVICE_NAME/config`, so you should be able to modify anything there (or set any files necessary) and restart your elasticsearch service.
