### ISSUE TITLE
elasticsearch:create fails due to invalid call to dokkupaas/wait

### ISSUE THREAD

**Issue by IlyaSemenov** [dokku/dokku-elasticsearch#40]
The latest version fails to create an Elasticsearch service:

```console
# dokku elasticsearch:create test
...
docker: Error response from daemon: oci runtime error: exec: "-p": executable file not found in $PATH.
```

The full gist is here: https://gist.github.com/IlyaSemenov/543a3c7252c9a5b4cb8e8c8a90475bda

I believe this is caused by this recent change in the wait plugin: https://github.com/dokku/docker-wait/commit/9db7b36505a539782d7ef3be049c2745b657eae0

Also, the versions, just in case:

```console
# dokku version
0.7.1

# (cd /var/lib/dokku/plugins/enabled/elasticsearch; git log --oneline|head -n 1)
e9c779d Fix command name

# docker images|grep wait
dokkupaas/wait                  0.2                 f191c874dade        3 weeks ago         9.077 MB
```

**Comment by josegonzalez** [comment]
Pull the latest version of dokkupaas/wait.

**Comment by IlyaSemenov** [comment]
@josegonzalez Right, I didn't realise it was using untagged version for waiting. (That was late in the evening :)

Question is, why do you pull the tagged version:

```
install
14:pull-docker-image "dokkupaas/wait:0.2"
```

but then don't use it?

```
functions
51:  docker run --rm --link "$SERVICE_NAME:$PLUGIN_COMMAND_PREFIX" dokkupaas/wait -p "$PLUGIN_DATASTORE_WAIT_PORT" > /dev/null
```

This will inevitably lead to problems.

**Comment by josegonzalez** [comment]
Oversight. Can you make a pull request fixing that?
