### ISSUE TITLE
Installing elasticsearch plugins

### ISSUE THREAD

**Issue by michaellatman** [dokku/dokku-elasticsearch#48]
How would one go about installing plugins in this elasticsearch dokku instance? Namely, I would like to install [the ingest attachment plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/5.x/ingest-attachment.html)

**Comment by josegonzalez** [comment]
The following should work:

```shell
docker exec $(dokku elasticsearch:info SERVICE --id) /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head
```

**Comment by michaellatman** [comment]
Thank you! Will this persist over restarts?

**Comment by josegonzalez** [comment]
Don't know, I don't remember if we mount the correct directory for plugins. Try it and see?

**Comment by seanfcarroll** [comment]
@michaellatman did it persist after the restart? Would you have a little time to document how it works in a pull request?

**Comment by dmr** [comment]
@michaellatman ingest-attachment is a plugin for elasticsearch version 5, I read that only 2.x is supported. --> Did you manage to get it running?

**Comment by cu12** [comment]
Couple of months ago I implemented this feature in a fork https://github.com/cu12/dokku-elasticsearch

I there's interest I could add this to upstream.

**Comment by dmr** [comment]
I'd be interested

**Comment by cu12** [comment]
ok, It shouldn't be hard to add this, some restructure is needed in my fork tho', due to changes in the internal layout of plugins.

**Comment by michaellatman** [comment]
@dmr @seanfcarroll I did not get to try it unfortunately. Sorry for the late reply.

**Comment by seanfcarroll** [comment]
@cu12 I'd be interested in that also.

@michaellatman no problem man. Thanks for your reply.

**Comment by josegonzalez** [comment]
I think the correct way to do this is to specify a custom image that has your desired plugins installed. If folks are still having this issue, please file a new ticket :)
