### ISSUE TITLE
Installing a custom elasticsearch image --> replace "docker pull "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION"?

### ISSUE THREAD

**Issue by dmr** [dokku/dokku-elasticsearch#50]
I'm trying to build my own elasticsearch image which requires a specific version and plugins and the plugin always executes 

```docker pull "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION"```

I think it would be more generic to only have one variable `ELASTICSEARCH_IMAGE="elasticsearch:2.3.3` which would allow me to replace this with a custom url that I like.

Maybe I understood docker pull wrong but is there a reason for the second variable?

**Comment by josegonzalez** [comment]
We pull an image and a version of that image. You can do `ELASTICSEARCH_IMAGE=dmr/yolo` and `ELASTICSEARCH_IMAGE_VERSION=latest` if you wanted. They are separate because they are separate, nothing more.

**Comment by dmr** [comment]
I was hoping that I could use a git repository as a source because I use private repositories. I try to use a url as a image but that does not work yet

**Comment by josegonzalez** [comment]
This issue was moved to dokku/dokku-redis#83

**Comment by khakulov** [comment]
```sh
export ELASTICSEARCH_IMAGE="docker.elastic.co/elasticsearch/elasticsearch"
export ELASTICSEARCH_IMAGE_VERSION="6.0.1"
dokku elasticsearch:create myinstance
```
