### ISSUE TITLE
CORS support?

### ISSUE THREAD

**Issue by dabeeeenster** [dokku/dokku-elasticsearch#52]
I'm trying to connect to my ES dokku instance with [ElasticHQ](http://www.elastichq.org/) but I'm getting CORS errors. Is there a way to expose the REST API and enable CORS support?

**Comment by josegonzalez** [comment]
You can `expose` the elasticsearch service, but we currently do not front elasticsearch with nginx or anything, so you would need to handle that part on your own in order to enable CORS. Sorry.

**Comment by impulse** [comment]
@josegonzalez how can I use a custom Nginx config with this plugin? I only found a way of getting it to work for a specific index with [default templates](http://dokku.viewdocs.io/dokku/configuration/nginx/#customizing-via-configuration-files-included-by-the-default-tem).

```sh
su dokku
# Get internal IP
dokku elasticsearch:info servicename
cd ~/api/nginx.conf.d
vim es.conf
```

~/api/nginx.conf.d/es.conf
```
location /yourindexname {
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Credentials' 'true';
    add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
    add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS';
    proxy_pass http://yourinternalip:9200;
}
```
