### ISSUE TITLE
Use docker version from elastic.co docker hub version is depreciated

### ISSUE THREAD

**Issue by ckazel** [dokku/dokku-elasticsearch#55]
Docker Hub shows following message and directs to docker.elastic.co/elasticsearch/elasticsearch.
Could you update it to use from elastic.co? 
DEPRECATED
This image has been deprecated in favor of the official elasticsearch image provided and maintained by elastic.co. The upstream images are available to pull via docker.elastic.co/elasticsearch/elasticsearch:[version] like 5.4.2. The images found here will receive no further updates once the 5.6.0 release is available upstream. Please adjust your usage accordingly.

**Comment by jalcine** [comment]
This can be changed using the options mentioned in the README.
However, yeah, this mainline repo shouldn't point at deprecated stuff.

@ckazel, perhaps a PR changing the values set in the configuration: https://github.com/dokku/dokku-elasticsearch/blob/master/config

**Comment by josegonzalez** [comment]
We don't support 5.x yet. The elasticsearch folks decided to do a bunch of fun things to their default container that makes upgrading... difficult at best. See #53 for more details.

As always, pull requests welcome.

**Comment by jalcine** [comment]
Thanks for the context!
