### ISSUE TITLE
Update to newer Elasticsearch

### ISSUE THREAD

**Issue by sotte** [dokku/dokku-elasticsearch#58]
I just wanted to try the Elasticsearch plugin but found out that only version 2.3 is supported. Are there any plans of updating to newer Elasticsearch versions? Say something around 6.2?

**Comment by josegonzalez** [comment]
Basically the newest versions of the image introduced issues with how we need to interact with elasticsearch to start it. If you'd like to submit a pull request to get us working with a newer version, that would be great.

See #53 for further investigation.
