### ISSUE TITLE
Problem when creating an elasticsearch service

### ISSUE THREAD

**Issue by templth** [dokku/dokku-elasticsearch#70]
Hello,

I try to create a service but got this error:

```
dokku elasticsearch:create myesservice
=====> Extracting config files
12e5e8f167f5df1b7fa6c60701d8782a3f322e697b63e52d7993442ed9e80f39
docker: Error response from daemon: endpoint with name dokku.elasticsearch.myesservice already exists in network bridge.
```

I did previously:

```
$ dokku elasticsearch:destroy myesservice
```

After run the create command, I have the following within Docker:

```
$ docker ps -a

CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS                     PORTS               NAMES
30ef765a1ed6        elasticsearch:6.7.1                             "/usr/local/bin/do..."   3 seconds ago       Created                                        dokku.elasticsearch.myesservice

```

I wonder if the service is correctly created...

Thanks for your help!

**Comment by josegonzalez** [comment]
Did the container removal fail? We run tests for this in CI, but if you can file a failing test for this, I can take a closer look.

**Comment by templth** [comment]
Thans for your answer!

With the command `dokku elasticsearch:destroy myesservice`, the container in docker is removed successfully...

Antoher strnge thing, I link this service with my app and I got this error when deploying:

```
remote: docker: Error response from daemon: Cannot link to a non running container: /dokku.elasticsearch.myesservice AS /musing_pasteur/dokku-elasticsearch-myesservice.
```

How can I debug things to detect what is broken?

**Comment by josegonzalez** [comment]
Is the container created when you run that?

**Comment by templth** [comment]
In fact, the container for the elasticsearch service isn't running because of the error:

```
Error response from daemon: endpoint with name dokku.elasticsearch.myesservice already exists in network bridge
Error: failed to start containers: 5f2b9678de67
```

**Comment by templth** [comment]
@josegonzalez I removed the endpoint from the network bridge:

```
docker network disconnect bridge dokku.elasticsearch.myesservice
```

and now I can start the elasticsearch service

**Comment by josegonzalez** [comment]
Are you using a custom network of some sort? The plugins almost certainly won't support that.

**Comment by josegonzalez** [comment]
If you want to file a test in this repository as a pull request for replicating this issue, I can maybe dig further, but otherwise I don't have time to dig into this at this time.

**Comment by templth** [comment]
No, I don't use a custom network...

**Comment by josegonzalez** [comment]
Oh I see what you mean.

You'll need to delete the currently existing/created container and _then_ start your service.

**Comment by templth** [comment]
Yes I finally started the service and app (with the link), but the value in the ELASTICSEARCH_URL isn't a reachable address...

**Comment by josegonzalez** [comment]
You'll need to unlink and relink.

**Comment by templth** [comment]
@josegonzalez it works now! thanks for your help!
