### ISSUE TITLE
sed: can't read /var/lib/dokku/services/elasticsearch/law/config/jvm.options: No such file or directory

### ISSUE THREAD

**Issue by erojs** [dokku/dokku-elasticsearch#77]
Hello 
I am new to use dokku,
When I install plugin and try to create Elasticsearch DB, 
`dokku elasticsearch:create law`

I get the info

=====> Extracting config files
c8bc49027001691de1f9324d26b3c4a8fcffef6c76523c31242b3e595f818d36
sed: can't read /var/lib/dokku/services/elasticsearch/law/config/jvm.options: No such file or directory

And when I use `dokku elasticsearch:info law` I get the info

cat: /var/lib/dokku/services/elasticsearch/law/ID: No such file or directory
cat: /var/lib/dokku/services/elasticsearch/law/ID: No such file or directory
=====> Container Information
       Config dir:          /var/lib/dokku/services/elasticsearch/law/config
       Data dir:            /var/lib/dokku/services/elasticsearch/law/data
       Dsn:                 http://dokku-elasticsearch-law:9200
       Exposed ports:       -                        
       Id:                                           
       Internal ip:                                  
       Links:               -                        
       Service root:        /var/lib/dokku/services/elasticsearch/law
       Status:              missing                  
       Version:                     

Is this normal? Or I need to do something to fix this ?
Thank you guys!

--
use digitalocean vps Ubuntu Dokku 0.17.9 on 18.04

**Comment by josegonzalez** [comment]
This should no longer be the case, and I believe it was a bug in the elasticsearch image.
