### ISSUE TITLE
Upgrade Elasticsearch version to 7.16.2

### ISSUE THREAD

**Issue by duffn** [dokku/dokku-elasticsearch#99]
## Description of problem

The plugin is using a vulnerable version of Elasticsearch. It should be upgraded to version 7.16.2 as per this Dependabot update: https://github.com/dokku/dokku-elasticsearch/pull/98

### Steps to Reproduce

1. Install the plugin

#### Actual Results

Version 7.14.2 is running: https://github.com/dokku/dokku-elasticsearch/blob/master/Dockerfile

<img width="461" alt="Screen Shot 2021-12-31 at 7 41 07 AM" src="https://user-images.githubusercontent.com/3457341/147828748-d9be6918-df5d-44eb-91aa-ba7c7cd77777.png">

#### Expected Results

The plugin should run Log4j patched version 7.16.2.

<img width="464" alt="Screen Shot 2021-12-31 at 7 41 16 AM" src="https://user-images.githubusercontent.com/3457341/147828755-04f13e9c-30a9-4bde-a6be-73beee2936e7.png">

### `dokku report APP_NAME` output

Affected in all apps that use the plugin.

### Additional information

- App container inspect output (if applicable) via `dokku ps:inspect APP_NAME`
- The nginx configuration (if applicable) via `dokku nginx:show-config APP_NAME`
- Link to the exact repository being deployed (if possible/applicable):
- Output of failing Dokku commands after running `dokku trace:on`
  (BEWARE: `trace:on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXX):

**Comment by josegonzalez** [comment]
This is done. Thanks for reporting.
